export const LOAD_RESTAURANTS = "LOAD_RESTAURANTS";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SET_ADDRESS = "SET_ADDRESS";
export const ADD_ORDER_ITEM = "ADD_ORDER_ITEM";
export const REMOVE_ORDER_ITEM = "REMOVE_ORDER_ITEM";
export const LOAD_ORDER = "LOAD_ORDER";